import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import { Links } from "../components/Links";
import { Main } from "../components/Main/Main";
import { Header } from "../components/Header";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  //状態の初期化
  const [Count,setCount] = useState(1);
  
  //状態を更新する
  const display_console = (e) => {
    setCount(Count =>Count +1)
    // console.log(Count);
  };

  
  
  return (  
    <>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <h1>{Count}</h1>
        <button onClick={display_console}>ボタン</button>
        <Header/>
        <Main page="index" />
        <Links />
      </main>
      
      </>
  );
}
