import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import { Links } from "../components/Links";
import { Main } from "../components/Main/Main";
import { Header } from "../components/Header";
import { useCallback, useEffect,useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  //状態の初期化
  const [count,setCount] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);

  
  //状態を更新する
  const display_console = useCallback(() => {
    console.log(count);
    if(count < 10){
      setCount(count =>count +1)
    }
    // console.log(count);
  },[count]);

  const handleChange = useCallback((e) => {
    if(e.target.value.length > 5){
      alert("5文字以内にしてください")
      return;
    }
    //スペースなどを取り除く
    setText(e.target.value.trim());
  },[]);

  const handleDisplay = useCallback(() =>{
    setIsShow((isShow) =>{            
      return isShow ? false : true;
    })
  },[])

  useEffect(() =>{
    // console.log("foo");
    document.body.style.backgroundColor = "lightblue"

    return () => {
      // console.log("bar");
      document.body.style.backgroundColor = ""
    }
  },[count]);

  
  
  return (  
    <>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      {isShow ? <h1>{count}</h1> : null}
        <button onClick={display_console}>ボタン</button>
        <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>
        <input type="text" value={text} onChange={handleChange}/>
        <Header/>
        <Main page="index" />
        <Links />
      </main>
      
      </>
  );
}
